### ISSUE TITLE
Evil Forker

### ISSUE THREAD

**Issue by Hyp3rSon1X** [ms-jpq/vm-in-docker#1]
Sry, I was the one who forked it. I thought i need to use this weird github actions thing to get an image out of it, but failed miserably anyway and finally found your dockerhub page with built images on it.

About your warning:

Does this thing not work at all? Or does it just need a bit more dirty work than what the finished version will require? 
The idea sure sounds nice though!

**Comment by ms-jpq** [comment]
it just needs a little bit work,

i want to make it possible to run as —net=host, and make the vm available on lan, its missing that.

once i fix it, it should be all good.

**Comment by Hyp3rSon1X** [comment]
Hey,
So I have this as my docker-compose file:

```version: '2.4'

services:
 windows-kvm:
    privileged: true
    image: msjpq/kvm-windows-build:latest
    cpu_count: 4
#   network_mode: host
    restart: unless-stopped
    environment:
      SCR_WIDTH: 1600
      SCR_HEIGHT: 900
      VM_NAME: wind
      PATH_PREFIX: /
      VNC_RESIZE: remote
      RECON_DELAY: 250
      PAGE_TITLE: KVM
    ports:
      - '5900:5900'
      - '1234:8080'
    volumes:
    - ./vm_data:/config
    - ./install_media:/install
```





What else am I missing to get this thing to run? Into the install_media folder I put my Windows iso. The vm_data is empty since I dont know what to put inside...

**Comment by ms-jpq** [comment]
sorry eh, everything is still subject to change, and I dont want to make a commitment now and break ur set up later.

I will revisit this repo when I have some free time. Ill let you know when im done :)

**Comment by zhang-xinsheng** [comment]
[cont-init.d] 00-kvm.sh: exited 0.
[cont-init.d] 00-nat.py: executing... 
Traceback (most recent call last):
  File "/var/run/s6/etc/cont-init.d/00-nat.py", line 190, in <module>
    main()
  File "/var/run/s6/etc/cont-init.d/00-nat.py", line 183, in main
    check_br()
  File "/var/run/s6/etc/cont-init.d/00-nat.py", line 66, in check_br
    if name in br_names:
  File "/var/run/s6/etc/cont-init.d/00-nat.py", line 63, in <genexpr>
    br_names = (br["ifname"] for br in bridges)
KeyError: 'ifname'
[cont-init.d] 00-nat.py: exited 1.
